/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import UIKit

var n0 = 0
var n1 = 1
var n2 = 2
var sum = 0

func evenFibonacciSum() -> Int {
    while n2 < 4000000 {
        if n2 % 2 == 0 {
            sum += n2
        }
        
        n0 = n1
        n1 = n2
        n2 += n0
    }
    
    return sum
}

print(evenFibonacciSum())
